### ISSUE TITLE
it always errors out when i try to launch application

### ISSUE THREAD

**Issue by veryepicusername123** [NotHammer043/nanoMIDIPlayer#5]
OS: Windows 11 Pro - Intel Core i7

Here's the error message when I try to launch NanoMidi v9.69.69:
Please fix this.
 _Traceback (most recent call last):
  File "nanoMIDIPlayer.py", line 2584, in <module>
  File "nanoMIDIPlayer.py", line 66, in __init__
  File "nanoMIDIPlayer.py", line 95, in showLogo
  File "nanoMIDIPlayer.py", line 139, in loadConfig
PermissionError: [Errno 13] Permission denied: 'C:\\WINDOWS\\system32\\config.json'_

**Comment by NotHammer043** [comment]
Only open nanoMIDIPlayer.exe from the folder itself, refrain from opening it from search or any quick-access menu. Alternatively you can pin the executable from your taskbar or create a shortcut.
